import Head from 'next/head'
import styles from '../styles/Home.module.css'
import  {client} from '../lib/client'
import ProductsGrid from '../components/product/ProductsGrid'
export default function Home({products,bannerData}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Sweetcommerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
      <main className={styles.main}>
        Hi there
        <ProductsGrid columnsStyle={['1','2','4','6']} headingText={'Buy something sweet:'} items={products}/>
      </main>

  
    </div>
  )

}


export const getServerSideProps = async () => {
  const query = '*[_type == "product"]';
  const products = await client.fetch(query);

  const bannerQuery = '*[_type == "banner"]';
  const bannerData = await client.fetch(bannerQuery);

  return {
    props: { products, bannerData }
  }
}